# Site settings
title: Numy
email: info@numy.io
description: A simple blog.
baseurl: "/zetsu"
url: "http://numyio.github.io"

author:
  name     : 'Numy Media'
  email    : info@numy.io
  url      : http://numyio.github.io
  facebook : http://facebook.com/numyio
  twitter  : http://twitter.com/numyio

github: https://github.com/numyio/zetsu
disqus_shortname: "https-numyio-github-io-zetsu"
google_analytics: # UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
